### ISSUE TITLE
Basic compilation is failing

### ISSUE THREAD

**Issue by ibnesayeed** [Nadorrano/cv-friggeri-x#4]
I cloned the repository, changed the directory and then ran the `xelatex` command which did not succeed.

I am using Elementary OS Loki (an Ubuntu 16.04 based distro).

```
$ git clone https://github.com/Nadorrano/cv-friggeri-x
$ cd cv-friggeri-x
$ xelatex cv 
...
(/usr/share/texlive/texmf-dist/tex/latex/biblatex/lbx/english.lbx)
No file cv.aux.
(/usr/share/texmf/tex/latex/tipa/t3cmr.fd)
Runaway argument?
\prg_do_nothing: \cs_gset_eq:NN \backslash \'::\exp_not:N 
! File ended while scanning use of \__tl_rescan:w.
<inserted text> 
                \par 
l.36 \begin{document}
                     ^^M
? 
```

**Comment by Nadorrano** [comment]
I can't reproduce this issue, it compiles fine with xelatex 2017. I see that Ubuntu 16.04 still uses texlive 2015, try upgrading the package together with biber/biblatex.

**Comment by ibnesayeed** [comment]
I can confirm that it compiled fine in `xelatex 2017`. However, installing `xelatex 2017` on Ubuntu 16.04 based OSes is painful, especially when an older version of the `xelatex` is already installed. I tried purging my previous installation and installed the new one from a PPA, but I ended up in a mess. Anyhow, I have built a Docker image now which seems to be working.
